sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

services:
 - docker

cache:
  directories:
  - download-cache

env:
  global:
    # - LUA_INCLUDE_DIR=$LUAJIT_INC
  matrix:
    # - NGINX_VERSION=1.10.0

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - cd ./deploy && ./run.sh