sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

services:
 - docker

cache:
  directories:
  - download-cache

env:
  global:
    # - LUA_INCLUDE_DIR=$LUAJIT_INC
  matrix:
    # - NGINX_VERSION=1.10.0

install:
  # - if [ ! -d download-cache ]; then mkdir download-cache; fi

script:
  - cd ./deploy && ./run.sh