#!/usr/bin/env bash

### BEGIN ###
# Author: idevz
# Since: 2018/03/12
# Description:   An entrypoint script in the parallels vm.
# prlctl exec golang 'sudo -Hiu z set_up'
### END ###

set -e

[ -z $PRLCTL_HOME ] && PRLCTL_HOME=/media/psf/runX
[ $HOME != '/home/z' ] && echo 'Are U Z ?' && exit 1
HOSTNAME=$(hostname)
BASE_DIR=$(dirname $(cd $(dirname "$0") && pwd -P)/$(basename "$0"))

# create a profile for each host such as envriment variable setting
create_profile() {
	[ -z "$1" ] && echo "empty profile content." && exit 1
	PROFILE_FILE=/etc/profile.d/idevz_prlctl_${HOSTNAME}.sh
	[ -f ${PROFILE_FILE} ] && sudo rm ${PROFILE_FILE}
	echo "$1" | sudo tee -a /etc/profile.d/idevz_prlctl_${HOSTNAME}.sh
	# sudo sh -c "echo zzz >> /etc/profile"
	sudo chmod +x ${PROFILE_FILE}
}

init_etc_profile() {
	cat ${PRLCTL_HOME}/zsh/etc-profile | sudo tee /etc/profile >/dev/null 2>&1
}

init_zsh() {
	cp -f ${PRLCTL_HOME}/zsh/.zshrc ~/.zshrc
	cat ${PRLCTL_HOME}/zsh/.zshrc | sudo tee /root/.zshrc >/dev/null 2>&1
}

init_gdb() {
	GDB_INIT_F=$(
		cat <<GDB_INIT
set history save on
set history filename ${PRLCTL_HOME}/gdb/$(hostname)/.gdb_history

define sbps
	save breakpoints ${PRLCTL_HOME}/gdb/$(hostname)/$(whoami).bps
	print "save the breakpoints to \"%s\"", "${PRLCTL_HOME}/gdb/$(hostname)/$(whoami).bps"
end
document sbps
    save break points
    Usage: sbps
end

define rbps
	source ${PRLCTL_HOME}/gdb/$(hostname)/$(whoami).bps
end
document rbps
    load the break points
    Usage: rbps
end

source ${PRLCTL_HOME}/gdb/$(hostname)/.gdbinit
source ${PRLCTL_HOME}/gdb/ext/tools.py
GDB_INIT
	)
	echo ${GDB_INIT_F} >${HOME}/.gdbinit
	echo ${GDB_INIT_F} | sudo tee /root/.gdbinit >/dev/null 2>&1
}

base_init() {
	init_etc_profile
	init_zsh
	init_gdb
	sudo touch /home/already_init
}

# check if already inited
[ ! -f /home/already_init ] && base_init

case ${1} in
rp | recreate_profile)
	BASE_DIR=$BASE_DIR/${HOSTNAME} && . $BASE_DIR/init
	create_profile "${PROFILE}"
	;;
*)
	BASE_DIR=$BASE_DIR/${HOSTNAME} && . $BASE_DIR/init
	init
	;;
esac
