kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: idevz-test-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5M
  storageClassName: local-storage
