#!/usr/bin/env bash

### BEGIN ###
# Author: idevz
# Since: 2018/03/12
# Description:       Set up Golang development environment.
# ./init.sh          Set up using $(pwd) as BASE_DIR, down which has go source and binaries.
#
# Environment variables that control init:
# GV: Golang version which you want to install.
# IT: installation type which you want to using, like "bin" to install from binary packages,
#     "src" to install from source, default using "bin".
# WS: your golang workspaces
### END ###

set -e

[ -z $PRLCTL_HOME ] && PRLCTL_HOME=/media/psf/runX

H_PROXY_ADDR="http://127.0.0.1:8118"
BASE_DIR=${BASE_DIR:-"$(readlink -f "$(dirname "$0")")"}
OUT_GOING_ACCOUNT_FILE=${OGA:-"out-accounts-info.zj"}

sudo_write() {
	local content="${1}"
	local file_name="${2}"
	local if_add=
	[ ! -z ${3} ] && if_add="-a"
	echo "${content}" | sudo tee ${if_add} "${file_name}" >/dev/null 2>&1
}

init_out_going() {
	source "${BASE_DIR}/${OUT_GOING_ACCOUNT_FILE}"
	sudo yum -y install epel-release python-pip privoxy
	sudo pip install --upgrade pip
	sudo pip install shadowsocks
	local shadowsocks_conf=
	shadowsocks_conf=$(
		cat <<SS_CONF
{
    "server":"${OUT_IP}",
    "server_port":${OUT_PORT},
    "local_address":"127.0.0.1",
    "local_port":1080,
    "password":"${OUT_PASWD}",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open":false
}
SS_CONF
	)
	sudo_write "${shadowsocks_conf}" "/etc/shadowsocks.json"

	local whitelist_conf=
	whitelist_conf=$(
		cat <<WT_CONF
{{alias}}
# 代理(socks5)
socks5 = +forward-override{forward-socks5 127.0.0.1:1080 .}
# 直连
direct = +forward-override{forward .}

# 所有网站走代理
{socks5}
/

# 以下网站走直连
{direct}
.ip.cn
WT_CONF
	)
	sudo_write "${whitelist_conf}" "/etc/privoxy/whitelist.action"
	sudo_write 'actionsfile whitelist.action' "/etc/privoxy/config" true

	local out_profile=
	out_profile=$(
		cat <<OUT_PROFILE
alias unstart_out="unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy"

proxy="${H_PROXY_ADDR}"
export HTTP_PROXY=\${proxy}
export HTTPS_PROXY=\${proxy}
export http_proxy=\${proxy}
export https_proxy=\${proxy}
export NO_PROXY="localhost, 127.0.0.1, ::1, ip.cn, chinaz.com"
OUT_PROFILE
	)
	sudo_write "${out_profile}" "/etc/profile" true
	source /etc/profile

	sudo_write "proxy=${H_PROXY_ADDR}" /etc/yum.conf true

	local out_service_unit=
	out_service_unit=$(
		cat <<OUT_SERVICE
[Unit]
Description=Out Going Service
After=network.target

[Service]
ExecStart=/bin/sslocal \
	    -c /etc/shadowsocks.json \
	    /dev/null 2>&1
ExecReload=/bin/kill -s HUP $MAINPID
Restart=on-failure
KillMode=process

[Install]
WantedBy=multi-user.target
OUT_SERVICE
	)
	sudo_write "${out_service_unit}" '/lib/systemd/system/out_going.service'
	sudo systemctl enable out_going
	sudo systemctl start out_going
	sudo systemctl start privoxy.service
	# systemctl -l status privoxy.service
}

sys_init() {
	sudo systemctl stop firewalld &&
		sudo systemctl disable firewalld
}

time_init() {
	sudo timedatectl set-timezone Asia/Shanghai
	sudo timedatectl set-ntp yes
}

sudo yum install -y patch
