#!/usr/bin/env bash

### BEGIN ###
# Author: idevz
# Since: 15:24:51 2019/07/15
# Description:       For what?
# kubectl-ls          simple usage.
#
# Environment variables that control this script:
#
### END ###

set -ex
BASE_DIR=$(dirname $(cd $(dirname "$0") && pwd -P)/$(basename "$0"))

# see if we have custom-columns-file defined
if [ ! -z "$1" ] && [ -f $PRLCTL_HOME/workspace/kube/columns/$1 ]; then
    kubectl get -o=custom-columns-file=$PRLCTL_HOME/workspace/kube/columns/$1 $@
else
    kubectl get $@
fi
